### ISSUE TITLE
Open Source Initiative

### ISSUE THREAD

**Issue by AhmedThahir** [FeddyLix17/Computer-Science#1]
We have started a progressive web app, where anyone can contributed short and crisp notes.
Would you be interested in contributing?

https://uni-notes.netlify.app/

**Comment by FeddyLix17** [comment]
@AhmedThahir
yeah man, in which way someone can contribute?

**Comment by AhmedThahir** [comment]
https://uni-notes.netlify.app/CONTRIBUTING/

You have your own notes, so whenever possible you could maybe audit our content.

**Comment by FeddyLix17** [comment]
@AhmedThahir yea gladly, i will take a look!
